{% set name = "prawcore" %}
{% set version = "2.1.0" %}
{% set sha256 = "afd8b2350461725cf317cd8e2e9ff6a2db34fa49e1498d53a3865b2516b84711" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.6.0,<3.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - prawcore

about:
  home: https://github.com/praw-dev/prawcore
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Low-level communication layer for PRAW 4+
  dev_url: https://github.com/praw-dev/prawcore

extra:
  recipe-maintainers:
    - djsutherland
